[project]
name = "cv-lab-1"
version = "0.1.0"
description = "CV Lab"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "pillow>=12.0.0",
    "scikit-image>=0.25.2",
]
